### ISSUE TITLE
Issues with Formatting json

### ISSUE THREAD

**Issue by the-butterfry** [jpmens/mqttwarn#294] opened 2018-03-13 19:18 UTC
I'm trying to get the Format to correctly parse out json received with the File handler plugin.
Here's an example string that is being received.
{"Time":"2018-03-13T20:16:55","DS18B20":{"Temperature":19.8},"TempUnit":"C"}

All I want to do is pull out the {Temperature} data into the File, discarding the rest. I can't seem to make it work. Any tips?
P.S.
I can make {time} work just fine, but as soon as I try to transform {temperature} is where the problems starts.

**Comment by amotl** [comment] 2018-04-13 16:15
Dear Cory,

thanks for reporting this. It is probably about the fact that "Temperature" is nested inside the main dictionary, right? Accessing the data through JSON Pointer might help here in the future, see also #303.

With kind regards,
Andreas.

**Comment by HillNet** [comment] 2018-08-14 06:39
Hi,

I've been using mqttwarn to parse mqtt topic's to influxdb. Works perfectly.

I'm now looking at parsing nested JSON messages and this is where I get stuck (I'm a self taught hobbiest).

I see there is a workaround for nested JSON included in README.md. Would you be able to advise if that will work with multiple payloads? This is my received JSON message:

`{
   "Time":"2018-08-14T07:21:45",
   "DS18B20-1":{
      "Id":"051693DD63FF",
      "Temperature":15.4
   },
   "DS18B20-2":{
      "Id":"0516941253FF",
      "Temperature":14.8
   },
   "SI7021":{
      "Temperature":12.2,
      "Humidity":99.9
   },
   "TempUnit":"C"
}`

I'm happy to "have a go" but if you could comment I'd appreciate it.

Many thanks,

Roland

**Comment by rgitzel** [comment] 2018-09-04 22:10
@HillNet I wrote the workaround in the README. It will work for your situation -- multiple temperature sensors with just one Sonoff?  nice, I want to try that one day :-) -- it will take just a little more coding.

The problem is that one message can create only one InfluxDb entry, by default. What you want is for each message to be processed twice. So we'll make mqttwarn do that.

Make two Python functions like in the example, one pulling out the "-1" value and the other pulling out the "-2" value.  Then create two topic sections in `mqttwarn.ini`, but don't name them based on the topic (see https://github.com/jpmens/mqttwarn#the-__topic__-sections).  "Temperature1" and "Temperature2" would do fine.

That should do it.

**Comment by HillNet** [comment] 2018-09-07 20:28
Thanks @rgitzel , I'll have a go!
_FYI, I'm running multiple sensors on a ESP8266 NodeMCU running the Tasmota firmware...._
Appreciate you taking time to respond.

**Comment by HillNet** [comment] 2018-09-30 05:09
Hi @rgitzel ,
I finally got back to this, and am fine with extracting one entry, but am failing at getting the message processed more than twice.

For reference, here is the nested JSON from TASMOTA

```
{
   "Time":"2018-09-07T21:29:44",
   "DS18B20":{
      "Temperature":13.4
   },
   "SI7021":{
      "Temperature":13.7,
      "Humidity":59.4
   },
   "BME280":{
      "Temperature":14.3,
      "Humidity":62.6,
      "Pressure":1016.7
   },
   "TempUnit":"C"
}
```
My functions.py entry looks like this:
```
import ast
import logging
import time
from datetime import datetime

def ds18b20_values(topic, data, srv=None):
    payload = ast.literal_eval(data["payload"])
    ts = datetime.strptime(payload["Time"], "%Y-%m-%dT%H:%M:%S")
    millis = long(time.mktime(ts.timetuple()) * 1000)
    temp = payload["DS18B20"]["Temperature"]
    d = dict( Topic = topic, Timestamp = millis, Temperature = temp )
    logging.debug(d)
    return d

def dht11_values(topic, data, srv=None):
    payload = ast.literal_eval(data["payload"])
    ts = datetime.strptime(payload["Time"], "%Y-%m-%dT%H:%M:%S")
    millis = long(time.mktime(ts.timetuple()) * 1000)
    temp = payload["SI7021"]["Humidity"]
    d = dict( Topic = topic, Timestamp = millis, Humidity = temp )
    logging.debug(d)
    return d
```


I took 

> then create two topic sections in mqttwarn.ini, but don't name them based on the topic

to mean the following, but I must have misunderstood as it dosn't "trap" the mqtt message:

```
[temperature1]
targets = log:info
alldata = ds18b20_values()
format  = weather,Topic={Topic} Temperature={Temperature} {Timestamp}

[humidity1]
targets = log:info
alldata = dht11_values()
format  = weather,Topic={Topic} Humidity={Humidity} {Timestamp}
```
The topic being published to mqtt is: `tele/e3_datalogger/SENSOR`

If you have time to provide further guidance I'd appreciate it.

Thanks.

**Comment by rgitzel** [comment] 2018-10-01 02:17
Hi @HillNet, you're close!

Add `topic = tele/e3_datalogger/SENSOR` to _both_ of the sections, and that should do it. 

```
[humidity1]
topic = tele/e3_datalogger/SENSOR
targets = log:info
...
```

I would also rename your second function to `si7021_values` to more accurate.

Cheers!

**Comment by HillNet** [comment] 2018-10-01 02:35
Thank you @rgitzel . This is awesome...I was sooo close. It is now working as you documented.

I need to do some work to get the "format" correct for influxdb, but that won't take too much now I have these single line data inputs.

I appreciate you taking time to help.

--
Roland

**Comment by rgitzel** [comment] 2018-10-01 14:14
@HillNet Try changing your format:
```
format  = value={Temperature}
```
The plugin will insert a tag for `topic` (albeit with underscores instead of slashes).  You can add other tags in there, see the plugin docs.

I suppose the examples I wrote are misleading, as they don't work with that plugin.

What I'm doing myself is writing full Influxdb lines out to topic `influx/input`.  Meanwhile I am running Telegraf, which pulls the Influxdb lines from the topic and writes them to InfluxDb.

This gave me more control:  I can use the timestamp from message, not from mqttwarn, and keep the original topic name.

I suppose another option would be to change the plugin to allow more control.  Hmmm.

**Comment by HillNet** [comment] 2018-10-01 19:48
Thank AGAIN @rgitzel, and yes I should have read the influxdb plugin guide last time :-(

The solution was to actually have `format = {Temperature}`, as format = value={Temperature} added a double "value":

`temperature,topic=tele_e3_datalogger_SENSOR value=value=16.4`

Anyway, I am now all sorted and can use TASMOTA on all my devices knowing mqttwarn can parse the nested JSON data to influxdb.

--
Best regards,

Roland

**Comment by jwyse** [comment] 2018-10-03 16:08
@HillNet You might consider pulling the latest version of mqttwarn. Judging by the code you copy/pasted from influxdb.py, you're not looking at the latest version (on your local machine, I assume?), which now includes some enhancements to the InfluxDB service (and expanded readme/format example).

**Comment by HillNet** [comment] 2018-10-03 22:47
Thanks @jwyse ,

You are of course correct. Rookie mistake of not updating....

I cloned the repo today and now have success. For the record, my `mqttwarn.ini` entry looks like:

```
[temperature1]
topic = tele/e3_datalogger/SENSOR
targets = influxdb:temperature
alldata = ds18b20_values()
format  = entity=ds18b20 value={Temperature} {Timestamp}
```
This gives the following log entry:

`DEBUG [influxdb] temperature,topic=tele_e3_datalogger_SENSOR,entity=ds18b20 value=17.2 1538563055000`

I truely have success now.

FYI @rgitzel 

Thanks for all the help. 

mqttwarn is an awesome piece of software @jpmens & @amotl 

--
Roland

**Comment by jacques42** [comment] 2019-10-05 20:55
I totally second @HillNet on mqttwarn being fantastic work  and also thanks for the influxdb service plugin - I use it frequently. 

Most recently I came across an error where using the InfluxDB service pluging, along with a simple format string it did not work. I am responding to this issue as reading through the above mine is related. 

But different from the formerly discussed solutions, I did not want to add an extra tag as I am fine and sufficient with the topic itself being added as tag:

**Inbound JSON String**
`{"RainTicks":"1"}
`

**mqttwarn.ini**
```; Raingauge Values
[MySensors/sensor-weather-1/Rain-1]
topic = MySensors/sensor-weather-1/Rain
targets = influxdb:influx-rain
format = {RainTicks}
```

which resulted in the following error log entry
`2019-10-05 22:32:01,418 WARNING [influxdb] POST request failed: (400) {"error":"unable to parse 'rain,topic=MySensors_sensor-weather-1_Rain,1': missing tag value"}
`

Looking at the code in `services/influxdb.py` it currently seems assumes that by appending `item.message`  after a comma, any message includes at least one more influx tag to start with:

```
  55:         data = measurement + ',' + tag + ',' + item.message
```
This did not work for me, hence I've enhanced the code to deal with different format string scenario's and in particular when no additional tags are provided. 

I'm not an expert coder but you may want to look at pull request #376 and eventually consider the changes to be added in the one or other way.

Thanks and best - Oliver

**Comment by amotl** [comment] 2019-11-20 03:15
As @HillNet signals goodness

> I truly have success now.

and #376 contributed by @jacques42 as been merged already, I believe it is safe to close this issue.

Please reopen if any of these things outlined within this discussion does not resolve the problem you have been observing, @the-butterfry.

**Comment by amotl** [comment] 2019-11-20 03:15
P.S.: As both a side note and a shameless plug from my side, I would like to mention that [Kotori](https://getkotori.org/) also received a Tasmota decoder the other day through https://github.com/daq-tools/kotori/commit/77b94fa1 and https://github.com/daq-tools/kotori/commit/5f5d9511.

[1] https://getkotori.org/docs/decoders/
[2] https://getkotori.org/docs/decoders/sonoff-tasmota.html

**Closed by amotl** 2019-11-20 03:15 UTC
